dateModified: 1755182104
email:
  fromEmail: hello@futurmedia.co.uk
  fromName: 'Futur Media'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    715bd30f-0e0c-467a-9556-20312d9ffa9a: craft-vite-ddev-starter # craft-vite-ddev-starter
    a0333b5b-25b4-44fc-9409-8164a8cf4f9c: 'Futur Media' # Futur Media
plugins:
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Futur Media'
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
